
#pragma once

#if defined(CONFIG_BOARD_ARDUINO_101)
#define CONFIG_MRAA_PIN_COUNT 14
#define CONFIG_MRAA_GPIO_COUNT 14
#define CONFIG_MRAA_AIO_COUNT 0
#define CONFIG_MRAA_I2C_COUNT 1
#define CONFIG_MRAA_SPI_COUNT 1
#define CONFIG_MRAA_UART_COUNT 1
#endif

